# Generated by Django 5.0 on 2023-12-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="erands",
            new_name="coffeeTea",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="happy",
            new_name="errands",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="home",
            new_name="foodGathering",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="landscape",
            new_name="happyHours",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="like",
            new_name="movies",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="person",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="movie",
            new_name="otherAdvice",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="tea",
            new_name="repairAdvice",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="swim",
            new_name="swimming",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="tv",
            new_name="television",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="address",
            new_name="zipCode",
        ),
    ]
