# Generated by Django 5.0 on 2023-12-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_userprofile_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
    ]
