# Generated by Django 5.0 on 2023-12-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_userprofile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
