# Generated by Django 5.0 on 2023-12-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_userprofile_sharepreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
