# Generated by Django 5.0 on 2023-12-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_remove_userprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
