# Generated by Django 5.0 on 2024-01-06 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_userprofile_childcare_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="confirmation_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="swimming",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
