# Generated by Django 5.0 on 2024-01-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_userprofile_confirmation_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="countryCode",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
