# Generated by Django 5.0 on 2024-01-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_userprofile_countrycode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="interests_updated",
            field=models.BooleanField(default=False),
        ),
    ]
