# Generated by Django 5.0 on 2024-01-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_userprofile_interests_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="errands",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="otherAdvice",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="televisionSports",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="art",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dog",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sports",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="childcare",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="coffeeTea",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="eldercare",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="foodGathering",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gardening",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="happyHours",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="movies",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="petcare",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="repairAdvice",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="rides",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="running",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="shopping",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="swimming",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tutoring",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="walking",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
