# Generated by Django 5.0 on 2024-01-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_remove_userprofile_errands_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="errands",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
