# Generated by Django 5.0 on 2024-01-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_remove_userprofile_errands"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="errands",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
