# Generated by Django 5.0 on 2024-01-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_remove_userprofile_errands"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="picture",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
