# Generated by Django 5.0 on 2024-01-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_userprofile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
