# Generated by Django 5.0 on 2024-01-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_alter_userprofile_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="zipCode",
            field=models.IntegerField(null=True),
        ),
    ]
