# Generated by Django 5.0 on 2024-01-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_alter_userprofile_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
