# Generated by Django 5.0 on 2024-01-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_alter_userprofile_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="user_pictures/"),
        ),
    ]
