# Generated by Django 5.0 on 2024-01-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_alter_userprofile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
