# Generated by Django 5.0 on 2024-01-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_alter_userprofile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
